version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
     - "8000:8000" 
    entrypoint: 
     - ./entrypoint.sh
    volumes:
     - ./:/app
    depends_on:
      - postgresdb
  
  postgredb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment: 
     - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/postgres/init.psql:/docker-enrtypoint-initdb.d/init.sql
    ports: 
     - "5432:5432"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/:/static
    depends_on:
      - postgresdb
      - web