# Generated by Django 3.2.9 on 2021-12-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_car_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='created_at',
            new_name='add_date',
        ),
    ]
